[build]
builder = "nixpacks"
buildCommand = "npx prisma generate --schema=backend/prisma/schema.prisma && npm run build --workspace=backend && npm run build --workspace=frontend"

[deploy]
startCommand = "npx prisma migrate deploy --schema=backend/prisma/schema.prisma && node backend/dist/main.js"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
